### ISSUE TITLE
sjlabelled::read_spss:  the argument enc does not work.

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjlabelled#4]
Hi, Daniel, 

I am trying to import a survey data that was encoded with big-5. 
sjlabelled::read_spss:  the argument enc does not work.
Please help check this issue. 

Thank you.
Best,
Frank Liu

**Comment by frankcsliu** [comment]
As this problem solved, could you remove the argument "enc" from the manual?

**Comment by strengejacke** [comment]
As `sjlabelled::read_spss()` simply wrap `haven::read_spss()`, encoding problems should be addressed there (i.e. please file an issue at the haven-repository).

`sjlabelled::read_spss()` has no `enc`-argument. The manual is up to date.

So is this issue solved due to one of the latest haven-updates?

**Comment by frankcsliu** [comment]
so far so good. Thank you.

**Comment by strengejacke** [comment]
haven has been updated, and I added an `enc`-argument to `read_spss()`. Could you please try if it works now?

**Comment by frankcsliu** [comment]
I confirm that haven (1.1.2) have indeed solved the encoding problem. I can now read the big5 file correctly via 
id15b <- read_sav("../Total.sav", encoding = "big5")

Please help activate the enc argument in sjlabelled::read_spss(). Thanks!

**Comment by strengejacke** [comment]
Yes, I'm planning tosubmit an update very soon, probably today or this weekend.
